# Based on https://codeberg.org/sail.black/serial-sphinx/src/branch/main/.woodpecker.yml

steps:
  flake8:
    image: python:3.9-buster
    when:
      event: pull_request
      branch: main
    commands:
      - python -m pip install --upgrade pip
      - python -m pip install flake8
      - python -m flake8 . --count --show-source --statistics

  pytest:
    image: python:${TAG}-buster
    when:
      event: pull_request
      branch: main
    commands:
      - ls
      - wget -O Miniforge3.sh "https://github.com/conda-forge/miniforge/releases/latest/download/Miniforge3-$(uname)-$(uname -m).sh"
      - bash Miniforge3.sh -b -p "${HOME}/conda"
      - . "${HOME}/conda/etc/profile.d/conda.sh"
      - conda activate
      - conda install -c conda-forge qgis movingpandas pytest
      - pytest .

matrix:
  TAG:
    - 3.9
    - 3.12.0b2